export enum EventName {
    PULSE ="PULSE",
    SEARCH_INSTRUMENT = "SEARCH_INSTRUMENT",
    LATEST_QUOTE = "LATEST_QUOTE",
    OPTION_LIST = "OPTION_LIST",
    FUTURE_LIST = "FUTURE_LIST",
    DISTINCT_FIELD_VALUES = "DISTINCT_FIELD_VALUES"
}
